# Generated by Django 5.2.4 on 2025-10-02 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaMutual',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.CharField(blank=True, max_length=22, null=True)),
                ('id_cuenta_mutual', models.AutoField(primary_key=True, serialize=False)),
                ('estatus_cuenta_mutual', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estatus*')),
                ('id_socio', models.IntegerField(blank=True, null=True, verbose_name='ID Socio*')),
                ('cuenta', models.IntegerField(blank=True, null=True, verbose_name='Cuenta*')),
                ('documento', models.CharField(blank=True, max_length=20, null=True, verbose_name='DNI')),
                ('cuit', models.CharField(blank=True, max_length=11, null=True, verbose_name='CUIT')),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('X', 'No binario')], max_length=1, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha Nacimiento')),
                ('caracteristica_pais_telefono', models.CharField(blank=True, max_length=2, null=True)),
                ('codigo_area_telefono', models.CharField(blank=True, max_length=4, null=True)),
                ('numero_telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('id_sg_usuario', models.CharField(blank=True, max_length=36, null=True, unique=True)),
                ('id_sg_cuenta', models.CharField(blank=True, max_length=36, null=True, unique=True)),
                ('cvu', models.CharField(blank=True, max_length=22, null=True, unique=True)),
                ('alias', models.CharField(blank=True, max_length=60, null=True)),
                ('razon_social', models.CharField(blank=True, max_length=80, null=True, verbose_name='Razón Social')),
            ],
            options={
                'verbose_name': 'Cuenta Mutual',
                'verbose_name_plural': 'Cuentas Mutuales',
                'db_table': 'cuenta_mutual',
                'ordering': ['id_cuenta_mutual'],
            },
        ),
        migrations.CreateModel(
            name='SgEntidadTipoDocumento',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.CharField(blank=True, max_length=22, null=True)),
                ('id_sg_entidad_tipo_documento', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('estatus_sg_entidad_tipo_documento', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estatus')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre Entidad Tipo Documento')),
            ],
            options={
                'verbose_name': 'SG Entidad Tipo Documento',
                'verbose_name_plural': 'SG Entidad Tipo Documento',
                'db_table': 'sg_entidad_tipo_documento',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='SgTipoCuenta',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.CharField(blank=True, max_length=22, null=True)),
                ('id_sg_tipo_cuenta', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('estatus_sg_tipo_cuenta', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estatus')),
                ('tipo_cuenta', models.CharField(max_length=60, verbose_name='Tipo Cuenta')),
            ],
            options={
                'verbose_name': 'SG Tipo Cuenta',
                'verbose_name_plural': 'SG Tipos Cuentas',
                'db_table': 'sg_tipo_cuenta',
                'ordering': ['tipo_cuenta'],
            },
        ),
        migrations.CreateModel(
            name='SgTipoPersona',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.CharField(blank=True, max_length=22, null=True)),
                ('id_sg_tipo_persona', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('estatus_sg_tipo_persona', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estatus')),
                ('tipo_persona', models.CharField(max_length=60, verbose_name='Tipo Persona')),
            ],
            options={
                'verbose_name': 'SG Tipo Persona',
                'verbose_name_plural': 'SG Tipos Personas',
                'db_table': 'sg_tipo_persona',
                'ordering': ['tipo_persona'],
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.CharField(blank=True, max_length=22, null=True)),
                ('id_sucursal', models.AutoField(primary_key=True, serialize=False)),
                ('estatus_sucursal', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estatus')),
                ('nombre_sucursal', models.CharField(max_length=50, verbose_name='Nombre sucursal')),
                ('domicilio_sucursal', models.CharField(max_length=50, verbose_name='Domicilio')),
                ('telefono_sucursal', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('email_sucursal', models.EmailField(max_length=50, verbose_name='Correo')),
                ('ws_url', models.CharField(max_length=50, verbose_name='WebService URL')),
                ('ws_token_acceso', models.CharField(max_length=50, verbose_name='Token Acceso')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'db_table': 'sucursal',
                'ordering': ['nombre_sucursal'],
            },
        ),
    ]
