# Generated by Django 5.2.4 on 2025-07-28 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.CharField(blank=True, max_length=22, null=True)),
                ('id_socio', models.AutoField(primary_key=True, serialize=False)),
                ('estatus_socio', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estatus*')),
                ('cuenta_socio', models.IntegerField(blank=True, null=True, verbose_name='Cuenta*')),
                ('tipo_cuenta', models.CharField(choices=[('C', 'Comun'), ('E', 'Especial'), ('D', 'Diferencial')], default='C', max_length=1, verbose_name='Tipo de Cuenta')),
                ('nombre_socio', models.CharField(max_length=50, verbose_name='Nombre Socio*')),
                ('telefono_socio', models.CharField(max_length=15, verbose_name='Teléfono*')),
                ('email_socio', models.EmailField(max_length=50, verbose_name='Email*')),
            ],
            options={
                'verbose_name': 'Socio',
                'verbose_name_plural': 'Socios',
                'db_table': 'socio',
                'ordering': ['nombre_socio'],
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.CharField(blank=True, max_length=22, null=True)),
                ('id_sucursal', models.AutoField(primary_key=True, serialize=False)),
                ('estatus_sucursal', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estatus')),
                ('nombre_sucursal', models.CharField(max_length=50, verbose_name='Nombre sucursal')),
                ('domicilio_sucursal', models.CharField(max_length=50, verbose_name='Domicilio')),
                ('telefono_sucursal', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('email_sucursal', models.EmailField(max_length=50, verbose_name='Correo')),
                ('ws_url', models.CharField(max_length=50, verbose_name='WebService URL')),
                ('ws_token_acceso', models.CharField(max_length=50, verbose_name='Token Acceso')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'db_table': 'sucursal',
                'ordering': ['nombre_sucursal'],
            },
        ),
    ]
