# Generated by Django 5.2.4 on 2025-09-16 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaMutual',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.CharField(blank=True, max_length=22, null=True)),
                ('id_cuenta_mutual', models.AutoField(primary_key=True, serialize=False)),
                ('estatus_cuenta_mutual', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estatus*')),
                ('id_socio', models.IntegerField(blank=True, null=True, verbose_name='ID Socio*')),
                ('cuenta', models.IntegerField(blank=True, null=True, verbose_name='Cuenta*')),
                ('documento', models.CharField(max_length=20)),
                ('id_sg_account', models.CharField(blank=True, max_length=64, unique=True)),
                ('cvu', models.CharField(blank=True, max_length=22, unique=True)),
                ('alias', models.CharField(blank=True, max_length=60)),
                ('id_sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maestros.sucursal', verbose_name='Sucursal*')),
                ('id_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuenta', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cuenta Mutual',
                'verbose_name_plural': 'Cuentas Mutuales',
                'db_table': 'cuenta_mutual',
                'ordering': ['id_user'],
            },
        ),
        migrations.DeleteModel(
            name='Socio',
        ),
        migrations.AddConstraint(
            model_name='cuentamutual',
            constraint=models.UniqueConstraint(fields=('id_user',), name='uniq_cuenta_por_user'),
        ),
    ]
