# Generated by Django 5.2.4 on 2025-09-17 19:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0003_cuentamutual_delete_socio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuentamutual',
            options={'ordering': ['id_cuenta_mutual'], 'verbose_name': 'Cuenta Mutual', 'verbose_name_plural': 'Cuentas Mutuales'},
        ),
        migrations.RemoveConstraint(
            model_name='cuentamutual',
            name='uniq_cuenta_por_user',
        ),
        migrations.AlterField(
            model_name='cuentamutual',
            name='alias',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='cuentamutual',
            name='cvu',
            field=models.CharField(blank=True, max_length=22, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cuentamutual',
            name='documento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cuentamutual',
            name='id_sg_account',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='cuentamutual',
            constraint=models.UniqueConstraint(condition=models.Q(('id_sg_account__isnull', False)), fields=('id_sg_account',), name='uniq_id_sg_account_not_null'),
        ),
        migrations.AddConstraint(
            model_name='cuentamutual',
            constraint=models.UniqueConstraint(condition=models.Q(('cvu__isnull', False)), fields=('cvu',), name='uniq_cvu_not_null'),
        ),
    ]
