# Generated by Django 5.2.4 on 2025-09-23 22:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0004_alter_cuentamutual_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cuentamutual',
            name='uniq_id_sg_account_not_null',
        ),
        migrations.AddField(
            model_name='cuentamutual',
            name='caracteristica_pais_telefono',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='cuentamutual',
            name='codigo_area_telefono',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='cuentamutual',
            name='cuit',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='CUIT'),
        ),
        migrations.AddField(
            model_name='cuentamutual',
            name='estado_cvu',
            field=models.CharField(blank=True, choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('CERRADO', 'Cerrado')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='cuentamutual',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuentamutual',
            name='id_entidad_tipo_documento',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='cuentamutual',
            name='id_sg_cuenta',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cuentamutual',
            name='id_sg_usuario',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cuentamutual',
            name='id_tipo_cuenta',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='cuentamutual',
            name='id_tipo_persona',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='cuentamutual',
            name='nro_cuenta_entidad',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cuentamutual',
            name='numero_telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cuentamutual',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('X', 'No binario')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='cuentamutual',
            name='documento',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='DNI'),
        ),
        migrations.AddConstraint(
            model_name='cuentamutual',
            constraint=models.UniqueConstraint(condition=models.Q(('id_sg_usuario__isnull', False)), fields=('id_sg_usuario',), name='uniq_id_sg_usuario_not_null'),
        ),
        migrations.AddConstraint(
            model_name='cuentamutual',
            constraint=models.UniqueConstraint(condition=models.Q(('id_sg_cuenta__isnull', False)), fields=('id_sg_cuenta',), name='uniq_id_sg_cuenta_not_null'),
        ),
    ]
