# Generated by Django 5.2.4 on 2025-09-24 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integraciones', '0001_initial'),
        ('maestros', '0005_remove_cuentamutual_uniq_id_sg_account_not_null_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuentamutual',
            name='estado_cvu',
        ),
        migrations.RemoveField(
            model_name='cuentamutual',
            name='id_sg_account',
        ),
        migrations.RemoveField(
            model_name='cuentamutual',
            name='nro_cuenta_entidad',
        ),
        migrations.AddField(
            model_name='cuentamutual',
            name='razon_social',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Razón Social'),
        ),
        migrations.AlterField(
            model_name='cuentamutual',
            name='caracteristica_pais_telefono',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='cuentamutual',
            name='codigo_area_telefono',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='cuentamutual',
            name='id_entidad_tipo_documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='integraciones.sgentidadtipodocumento'),
        ),
        migrations.AlterField(
            model_name='cuentamutual',
            name='id_tipo_cuenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='integraciones.sgtipocuenta'),
        ),
        migrations.AlterField(
            model_name='cuentamutual',
            name='id_tipo_persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='integraciones.sgtipopersona'),
        ),
        migrations.AlterField(
            model_name='cuentamutual',
            name='numero_telefono',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
