# Generated by Django 5.2.4 on 2025-09-24 03:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SgEntidadTipoDocumento',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.CharField(blank=True, max_length=22, null=True)),
                ('id_sg_entidad_tipo_documento', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estatus_sg_entidad_tipo_documento', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estatus')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre Entidad Tipo Documento')),
                ('id_user', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'SG Entidad Tipo Documento',
                'verbose_name_plural': 'SG Entidad Tipo Documento',
                'db_table': 'sg_entidad_tipo_documento',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='SgTipoCuenta',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.CharField(blank=True, max_length=22, null=True)),
                ('id_sg_tipo_cuenta', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estatus_sg_tipo_cuenta', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estatus')),
                ('tipo_cuenta', models.CharField(max_length=60, verbose_name='Tipo Cuenta')),
                ('id_user', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'SG Tipo Cuenta',
                'verbose_name_plural': 'SG Tipos Cuentas',
                'db_table': 'sg_tipo_cuenta',
                'ordering': ['tipo_cuenta'],
            },
        ),
        migrations.CreateModel(
            name='SgTipoPersona',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.CharField(blank=True, max_length=22, null=True)),
                ('id_sg_tipo_persona', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estatus_sg_tipo_persona', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estatus')),
                ('tipo_persona', models.CharField(max_length=60, verbose_name='Tipo Persona')),
                ('id_user', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'SG Tipo Persona',
                'verbose_name_plural': 'SG Tipos Personas',
                'db_table': 'sg_tipo_persona',
                'ordering': ['tipo_persona'],
            },
        ),
    ]
