# Generated by Django 5.2.4 on 2025-09-25 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integraciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sgentidadtipodocumento',
            name='id_sg_entidad_tipo_documento',
            field=models.CharField(max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sgtipocuenta',
            name='id_sg_tipo_cuenta',
            field=models.CharField(max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sgtipopersona',
            name='id_sg_tipo_persona',
            field=models.CharField(max_length=36, primary_key=True, serialize=False),
        ),
    ]
