# Generated by Django 5.2.4 on 2025-09-16 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_user_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_sucursal',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID Sucursal'),
        ),
    ]
